services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: